### ISSUE TITLE
crash: concurrent map writes

### ISSUE THREAD

**Issue by jon-walton** [juliosueiras/terraform-lsp#38]
Hi, I'm getting a crash in the lsp, unfortunately I'm not sure which part of my terraform config is causing it

LSP v0.0.9
Terraform extension 1.4.0
OS: Windows

```text
2019/11/04 11: 05: 22 Server started
fatal error: concurrent map writes

goroutine 50 [running]:
runtime.throw(0x100893b, 0x15)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/panic.go:608 +0x79 fp=0xc00000b8a8 sp=0xc00000b878 pc=0x42d889
runtime.mapassign_faststr(0xe991a0, 0xc000394c90, 0xc000070300, 0x57, 0x1957468)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/map_faststr.go:199 +0x3e1 fp=0xc00000b910 sp=0xc00000b8a8 pc=0x412911
main.TextDocumentDidOpen(0x11c8580, 0xc00044a180, 0xc000070240, 0x5e, 0xc00007f030, 0x9, 0x1, 0xc0002a0000, 0xe02, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:471 +0xf4 fp=0xc00000b9c0 sp=0xc00000b910 pc=0xd9c9e4
runtime.call128(0xc0002e4390, 0x1040ee8, 0xc00052a240, 0x4800000058)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:524 +0x59 fp=0xc00000ba50 sp=0xc00000b9c0 pc=0x4568f9
reflect.Value.call(0xe8d440, 0x1040ee8, 0x13, 0xff7573, 0x4, 0xc00044a240, 0x2, 0x2, 0xc00051a380, 0xc00000bdc8, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:447 +0x45b fp=0xc00000bd18 sp=0xc00000ba50 pc=0x4c5dfb
reflect.Value.Call(0xe8d440, 0x1040ee8, 0x13, 0xc00044a240, 0x2, 0x2, 0xe51100, 0xc00044a240, 0x1)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:308 +0xab fp=0xc00000bd80 sp=0xc00000bd18 pc=0x4c586b
reflect.Value.Call-fm(0xc00044a240, 0x2, 0x2, 0x1, 0xc000004660, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67 fp=0xc00000bdd8 sp=0xc00000bd80 pc=0x5670a7
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11c8580, 0xc00044a180, 0xc00007bcc0, 0xc00007bb30, 0xc000527ee8, 0x10, 0xc000527ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232 fp=0xc00000be90 sp=0xc00000bdd8 pc=0x566d22
github.com/creachadair/jrpc2/handler.Func.Handle(0xc0002054e0, 0x11c8580, 0xc00044a180, 0xc00007bcc0, 0x0, 0x0, 0x11c8580, 0xc00044a180)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b fp=0xc00000bed8 sp=0xc00000be90 pc=0x56592b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c83c0, 0x11c8500, 0xc00007e080, 0x11bd8e0, 0xc0002054e0, 0xc00007bcc0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7 fp=0xc00000bf60 sp=0xc00000bed8 pc=0x55e997
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc00007ef00, 0xc0000c83c0, 0xc0002e81b0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108 fp=0xc00000bfc8 sp=0xc00000bf60 pc=0x561678
runtime.goexit()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00000bfd0 sp=0xc00000bfc8 pc=0x4583e1
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000c83c8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc0000c83c0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/creachadair/jrpc2.(*Server).Wait(0xc0000c83c0, 0x1, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:368 +0x38
main.main()
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:617 +0x515

goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000bd7c0)
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:154 +0x107
created by go.opencensus.io/stats/view.init.0
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:32 +0x5e

goroutine 21 [syscall]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sigqueue.go:139 +0xa3
os/signal.loop()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/signal/signal_unix.go:29 +0x48

goroutine 28 [syscall, locked to thread]:
syscall.Syscall6(0x7ffed6962410, 0x5, 0x744, 0xc000399000, 0x1000, 0xc00000fb24, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/syscall_windows.go:183 +0xfc
syscall.ReadFile(0x744, 0xc000399000, 0x1000, 0x1000, 0xc00000fb24, 0x0, 0xc000528080, 0xc0003d6801)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/syscall/zsyscall_windows.go:313 +0xd5
syscall.Read(0x744, 0xc000399000, 0x1000, 0x1000, 0xa, 0x0, 0x8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/syscall/syscall_windows.go:295 +0x6f
internal/poll.(*FD).Read(0xc0000ae000, 0xc000399000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_windows.go:479 +0x1b3
os.(*File).read(0xc0000ac000, 0xc000399000, 0x1000, 0x1000, 0x538a55, 0xc0003d6960, 0xc000444490)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/file_windows.go:207 +0x55
os.(*File).Read(0xc0000ac000, 0xc000399000, 0x1000, 0x1000, 0xc0003d6960, 0xe27a00, 0xc0000d0620)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/file.go:108 +0x70
bufio.(*Reader).fill(0xc0000bb440)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/bufio/bufio.go:100 +0x116
bufio.(*Reader).ReadSlice(0xc0000bb440, 0xa, 0xffffffffffffffff, 0x0, 0xc0003d6960, 0xe27a00, 0xe994a0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/bufio/bufio.go:341 +0x3d
bufio.(*Reader).ReadBytes(0xc0000bb440, 0xc00000fe0a, 0xc00000fe58, 0x40bcd9, 0xc000096c90, 0x30, 0x28)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/bufio/bufio.go:419 +0x77
bufio.(*Reader).ReadString(0xc0000bb440, 0x42f70a, 0xc00000fe18, 0x4554b0, 0xc00006f800, 0x4)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/bufio/bufio.go:459 +0x3f
github.com/creachadair/jrpc2/channel.(*hdr).Recv(0xc0000bb4a0, 0xeb02a0, 0xc0002e2a80, 0xc000096c90, 0x1, 0x0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/channel/hdr.go:79 +0x80
github.com/creachadair/jrpc2.(*Server).read(0xc0000c83c0, 0x1ce0000, 0xc0000bb4a0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:434 +0x7e
github.com/creachadair/jrpc2.(*Server).Start.func1(0xc0000c83c0, 0x11c4900, 0xc0000bb4a0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:106 +0x96
created by github.com/creachadair/jrpc2.(*Server).Start
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:106 +0x16a

goroutine 29 [runnable]:
sync.(*Mutex).Lock(0xc00038b710)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/mutex.go:72 +0x2cd
sync.(*Cond).Wait(0xc00021d240)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:57 +0xaf
github.com/creachadair/jrpc2.(*Server).nextRequest(0xc0000c83c0, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:155 +0x96
github.com/creachadair/jrpc2.(*Server).serve(0xc0000c83c0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:132 +0x82
github.com/creachadair/jrpc2.(*Server).Start.func2(0xc0000c83c0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:109 +0x5a
created by github.com/creachadair/jrpc2.(*Server).Start
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:109 +0x18c

goroutine 51 [semacquire]:
sync.runtime_Semacquire(0xc00007ef08)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc00007ef00)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/creachadair/jrpc2.(*Server).dispatch.func2(0xc000000008, 0x1041670)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:195 +0x63
github.com/creachadair/jrpc2.(*Server).serve.func1(0xc0000c83c0, 0xc00052a1e0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:140 +0x56
created by github.com/creachadair/jrpc2.(*Server).serve
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:138 +0x74

goroutine 66 [runnable]:
sync.(*Map).dirtyLocked(0x193ac00)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/map.go:360 +0x12c
sync.(*Map).LoadOrStore(0x193ac00, 0xfe49e0, 0xf05340, 0xe30a40, 0xc000204380, 0xe97f00, 0x0, 0x784c0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/map.go:227 +0x462
encoding/json.cachedTypeFields(0x11d3620, 0xf05340, 0x45147a, 0xf05340, 0x784c0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:1256 +0x145
encoding/json.newStructEncoder(0x11d3620, 0xf05340, 0xec7fc0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:653 +0x57
encoding/json.newTypeEncoder(0x11d3620, 0xf05340, 0xf05301, 0xeb3f40)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:425 +0x2bc
encoding/json.typeEncoder(0x11d3620, 0xf05340, 0x99)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:377 +0x1a7
encoding/json.valueEncoder(0xf05340, 0xc0002e4480, 0x99, 0xfdcf80)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:351 +0x63
encoding/json.(*encodeState).reflectValue(0xc0000ce000, 0xf05340, 0xc0002e4480, 0x99, 0x1930100)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:333 +0x46
encoding/json.(*encodeState).marshal(0xc0000ce000, 0xf05340, 0xc0002e4480, 0x30100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:305 +0xfb
encoding/json.Marshal(0xf05340, 0xc0002e4480, 0xc0002e4480, 0x0, 0x193c280, 0xc0001a7848, 0x413165)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:160 +0x59
github.com/creachadair/jrpc2.(*Server).Push(0xc0000c83c0, 0x11c8580, 0xc0002e42d0, 0x10155dd, 0x1f, 0xf05340, 0xc0002e4480, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:334 +0x49b
main.TextDocumentPublishDiagnostics(0xc0000c83c0, 0x11c8580, 0xc0002e42d0, 0xc00003a180, 0x59, 0x1957468, 0x0, 0x0, 0x52, 0xee9b00)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:583 +0xbd
main.TextDocumentDidOpen(0x11c8580, 0xc0002e42d0, 0xc00003a180, 0x59, 0xc00038a150, 0x9, 0x1, 0xc0000e8400, 0x3fa, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:473 +0x1ff
reflect.Value.call(0xe8d440, 0x1040ee8, 0x13, 0xff7573, 0x4, 0xc0002e4360, 0x2, 0x2, 0x193c280, 0xc0001a7dc8, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xe8d440, 0x1040ee8, 0x13, 0xc0002e4360, 0x2, 0x2, 0xe51100, 0xc0002e4360, 0x1)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc0002e4360, 0x2, 0x2, 0x1, 0xc000204220, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11c8580, 0xc0002e42d0, 0xc0002e0140, 0xc00021d2b0, 0xc000197ee8, 0x10, 0xc000197ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc0002054e0, 0x11c8580, 0xc0002e42d0, 0xc0002e0140, 0x0, 0x0, 0x11c8580, 0xc0002e42d0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c83c0, 0x11c8500, 0xc00007e080, 0x11bd8e0, 0xc0002054e0, 0xc0002e0140, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc00038a050, 0xc0000c83c0, 0xc00037ee10)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141

goroutine 67 [semacquire]:
sync.runtime_Semacquire(0xc00038a058)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc00038a050)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/creachadair/jrpc2.(*Server).dispatch.func2(0x8, 0x1041670)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:195 +0x63
github.com/creachadair/jrpc2.(*Server).serve.func1(0xc0000c83c0, 0xc0004480c0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:140 +0x56
created by github.com/creachadair/jrpc2.(*Server).serve
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:138 +0x74

goroutine 36 [semacquire]:
sync.runtime_Semacquire(0xc00038a1f8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc00038a1f0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x6b
encoding/json.typeEncoder.func1(0xc0004562c0, 0xf05340, 0xc0003942a0, 0x99, 0xc0001a0100)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:369 +0x3a
encoding/json.(*encodeState).reflectValue(0xc0004562c0, 0xf05340, 0xc0003942a0, 0x99, 0xf00100)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:333 +0x89
encoding/json.(*encodeState).marshal(0xc0004562c0, 0xf05340, 0xc0003942a0, 0xc0000d0100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:305 +0xfb
encoding/json.Marshal(0xf05340, 0xc0003942a0, 0xc0003942a0, 0x0, 0xc0004c2000, 0xc0001a3848, 0x413165)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/encode.go:160 +0x59
github.com/creachadair/jrpc2.(*Server).Push(0xc0000c83c0, 0x11c8580, 0xc000394150, 0x10155dd, 0x1f, 0xf05340, 0xc0003942a0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:334 +0x49b
main.TextDocumentPublishDiagnostics(0xc0000c83c0, 0x11c8580, 0xc000394150, 0xc000478000, 0x5a, 0x1957468, 0x0, 0x0, 0x53, 0xee9b00)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:583 +0xbd
main.TextDocumentDidOpen(0x11c8580, 0xc000394150, 0xc000478000, 0x5a, 0xc0000320b0, 0x9, 0x15, 0xc000118480, 0x404, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:473 +0x1ff
reflect.Value.call(0xe8d440, 0x1040ee8, 0x13, 0xff7573, 0x4, 0xc000394180, 0x2, 0x2, 0xc0004c2000, 0xc0001a3dc8, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xe8d440, 0x1040ee8, 0x13, 0xc000394180, 0x2, 0x2, 0xe51100, 0xc000394180, 0x1)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc000394180, 0x2, 0x2, 0x1, 0xc000386020, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11c8580, 0xc000394150, 0xc00021c0c0, 0xc00021c130, 0xc000193ee8, 0x10, 0xc000193ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc0002054e0, 0x11c8580, 0xc000394150, 0xc00021c0c0, 0x0, 0x0, 0x11c8580, 0xc000394150)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c83c0, 0x11c8500, 0xc00007e080, 0x11bd8e0, 0xc0002054e0, 0xc00021c0c0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc000032090, 0xc0000c83c0, 0xc00047a090)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141

goroutine 37 [semacquire]:
sync.runtime_Semacquire(0xc000032098)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc000032090)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/creachadair/jrpc2.(*Server).dispatch.func2(0x8, 0x1041670)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:195 +0x63
github.com/creachadair/jrpc2.(*Server).serve.func1(0xc0000c83c0, 0xc0002ea240)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:140 +0x56
created by github.com/creachadair/jrpc2.(*Server).serve
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:138 +0x74

goroutine 82 [runnable]:
encoding/json.checkValid(0xc000427000, 0xf5d, 0x1000, 0xc00019c028, 0xc000068800, 0x40c5ff)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/scanner.go:25 +0x14c
encoding/json.Unmarshal(0xc000427000, 0xf5d, 0x1000, 0xe16300, 0xc000068800, 0xe16300, 0xc000068800)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/encoding/json/decode.go:101 +0x6d
github.com/creachadair/jrpc2.(*Request).UnmarshalParams(0xc000068780, 0xe16300, 0xc000068800, 0xe16300, 0xc000068800)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/base.go:74 +0x73
github.com/creachadair/jrpc2/handler.newHandler.func4(0xc000068780, 0x30, 0x30, 0xf6fb20, 0xc0004b9ec8, 0x55acc9)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:179 +0xae
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11c8580, 0xc0004385d0, 0xc000068780, 0xc0000687f0, 0xc0004b9ee8, 0x10, 0xc0004b9ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:217 +0x6e
github.com/creachadair/jrpc2/handler.Func.Handle(0xc0002054e0, 0x11c8580, 0xc0004385d0, 0xc000068780, 0x0, 0x0, 0x11c8580, 0xc0004385d0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c83c0, 0x11c8500, 0xc00007e080, 0x11bd8e0, 0xc0002054e0, 0xc000068780, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc0003d2010, 0xc0000c83c0, 0xc0001ac000)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141

goroutine 83 [semacquire]:
sync.runtime_Semacquire(0xc0003d2018)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc0003d2010)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/creachadair/jrpc2.(*Server).dispatch.func2(0x8, 0x1041670)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:195 +0x63
github.com/creachadair/jrpc2.(*Server).serve.func1(0xc0000c83c0, 0xc0000ba060)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:140 +0x56
created by github.com/creachadair/jrpc2.(*Server).serve
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:138 +0x74
[Info  - 11:05:22 AM] Connection to server got closed. Server will restart.
```

**Comment by terrytsay** [comment]
I ran into this as well - and upon some experimenting, the issue went away after I uninstalled Azure Terraform from Microsoft. I am guessing that it uses a language server too and was trying to lock the same thing.
